import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Check, Lock, Play } from 'lucide-react-native';
import { BottomTabScreenProps } from '@react-navigation/bottom-tabs';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { Screen } from '../components/Screen';
import { ProgressBar } from '../components/ProgressBar';
import { SectionHeader } from '../components/SectionHeader';
import { colors, radii, spacing, typography } from '../constants/theme';
import { belts } from '../constants/belts';
import { useAuth } from '../contexts/AuthContext';
import type { MainTabParamList, RootStackParamList } from '../navigation/types';

type Props = BottomTabScreenProps<MainTabParamList, 'Journey'>;
export function JourneyScreen({ navigation }: Props) {
  const { profile } = useAuth(); const currentIndex = belts.findIndex((item) => item.id === (profile?.current_belt ?? 'white')); const rootNavigation = navigation.getParent<NativeStackNavigationProp<RootStackParamList>>(); const progress = Math.min((profile?.xp ?? 0) / 400, 1);
  return <Screen><Text style={styles.eyebrow}>O CAMINHO É SEU</Text><Text style={styles.title}>Jornada</Text><Text style={styles.subtitle}>Uma faixa de cada vez. Cada conversa te leva mais longe.</Text><View style={styles.currentCard}><View style={styles.currentBadge}><Text style={styles.currentBadgeText}>{profile?.cefr_level ?? 'A0'}</Text></View><View style={styles.currentBody}><Text style={styles.currentLabel}>VOCÊ ESTÁ AQUI</Text><Text style={styles.currentTitle}>{belts[currentIndex]?.name ?? 'Faixa Branca'}</Text><ProgressBar value={progress} color={colors.goldBright} /><Text style={styles.currentMeta}>{Math.round(progress * 100)}% da faixa · {profile?.xp ?? 0} XP</Text></View></View><SectionHeader title="As faixas" /><View style={styles.timeline}>{belts.map((belt, index) => { const unlocked = index <= currentIndex; const active = index === currentIndex; return <View key={belt.id} style={styles.timelineRow}><View style={styles.rail}>{index !== 0 && <View style={styles.railLine} />}<View style={[styles.node, { backgroundColor: unlocked ? belt.color : colors.surfaceMuted }, active && styles.activeNode]}>{unlocked ? <Check size={15} color={belt.id === 'white' ? colors.background : colors.white} strokeWidth={3} /> : <Lock size={13} color={colors.textFaint} />}</View>{index !== belts.length - 1 && <View style={styles.railLine} />}</View><Pressable disabled={!unlocked} onPress={() => rootNavigation?.navigate('Lesson', { lessonId: index < 2 ? 'lesson-1' : 'lesson-3' })} style={[styles.beltCard, active && styles.activeCard, !unlocked && styles.lockedCard]}><View style={styles.beltCardTop}><View><Text style={styles.beltName}>{belt.name}</Text><Text style={styles.beltCEFR}>{belt.cefr} · {belt.title}</Text></View><Text style={[styles.beltStatus, { color: unlocked ? colors.gold : colors.textFaint }]}>{active ? 'ATUAL' : unlocked ? 'DESBLOQUEADA' : 'BLOQUEADA'}</Text></View><Text style={styles.beltDescription}>{belt.description}</Text>{active && <ProgressBar value={progress} color={belt.color} height={6} />}</Pressable></View>; })}</View></Screen>;
}

const styles = StyleSheet.create({ eyebrow: { ...typography.caption, color: colors.redBright, letterSpacing: 1.6, marginTop: spacing.sm }, title: { ...typography.display, color: colors.text, marginTop: 6 }, subtitle: { ...typography.body, color: colors.textMuted, marginTop: spacing.sm, marginBottom: spacing.xl }, currentCard: { flexDirection: 'row', gap: spacing.md, padding: spacing.md, backgroundColor: '#211B11', borderRadius: radii.lg, borderWidth: 1, borderColor: colors.goldSoft, marginBottom: spacing.xl }, currentBadge: { width: 58, height: 58, borderRadius: 29, backgroundColor: colors.gold, alignItems: 'center', justifyContent: 'center' }, currentBadgeText: { ...typography.h2, color: colors.background }, currentBody: { flex: 1, gap: 6 }, currentLabel: { ...typography.caption, color: colors.gold }, currentTitle: { ...typography.body, color: colors.text, fontWeight: '800' }, currentMeta: { ...typography.caption, color: colors.textMuted, letterSpacing: 0 }, timeline: { gap: spacing.sm }, timelineRow: { flexDirection: 'row', gap: spacing.sm, minHeight: 106 }, rail: { width: 30, alignItems: 'center' }, railLine: { flex: 1, width: 1, backgroundColor: colors.border }, node: { width: 27, height: 27, borderRadius: 14, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: colors.background }, activeNode: { borderColor: colors.gold, transform: [{ scale: 1.12 }] }, beltCard: { flex: 1, padding: spacing.md, backgroundColor: colors.surface, borderRadius: radii.md, borderWidth: 1, borderColor: colors.border, marginBottom: spacing.sm }, activeCard: { borderColor: colors.goldSoft, backgroundColor: '#1F1A12' }, lockedCard: { opacity: 0.55 }, beltCardTop: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm }, beltName: { ...typography.body, color: colors.text, fontWeight: '800' }, beltCEFR: { ...typography.caption, color: colors.textMuted, marginTop: 2, letterSpacing: 0 }, beltStatus: { ...typography.caption, fontSize: 9 }, beltDescription: { ...typography.body, color: colors.textMuted, fontSize: 13, marginTop: 9, marginBottom: 10 } });
