import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { ArrowRight, CheckCircle2, Clock3, Lock, PlayCircle } from 'lucide-react-native';
import { BottomTabScreenProps } from '@react-navigation/bottom-tabs';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { Screen } from '../components/Screen';
import { DemoBanner } from '../components/DemoBanner';
import { ProgressBar } from '../components/ProgressBar';
import { SectionHeader } from '../components/SectionHeader';
import { colors, radii, spacing, typography } from '../constants/theme';
import { belts } from '../constants/belts';
import { lessons } from '../data/lessons';
import { useAuth } from '../contexts/AuthContext';
import type { MainTabParamList, RootStackParamList } from '../navigation/types';

type Props = BottomTabScreenProps<MainTabParamList, 'Lessons'>;
export function LessonsScreen({ navigation }: Props) {
  const { profile, progress, demoMode } = useAuth(); const currentIndex = belts.findIndex((item) => item.id === (profile?.current_belt ?? 'white')); const rootNavigation = navigation.getParent<NativeStackNavigationProp<RootStackParamList>>();
  return <Screen><Text style={styles.eyebrow}>TREINO DIÁRIO</Text><Text style={styles.title}>Lições</Text><Text style={styles.subtitle}>Pequenas sessões. Grandes mudanças.</Text>{demoMode && <DemoBanner />}<View style={styles.streakCard}><View><Text style={styles.streakLabel}>META DE HOJE</Text><Text style={styles.streakTitle}>Uma lição para manter o ritmo.</Text></View><Text style={styles.streakValue}>{profile?.streak ?? 0}<Text style={styles.streakUnit}>d</Text></Text></View><SectionHeader title="Sua próxima lição" /><View style={styles.list}>{lessons.map((lesson, index) => { const beltIndex = belts.findIndex((belt) => belt.id === lesson.belt); const completed = progress.some((item) => item.lesson_id === lesson.id && item.completed); const unlocked = lesson.unlocked && beltIndex <= currentIndex; return <Pressable key={lesson.id} disabled={!unlocked} onPress={() => rootNavigation?.navigate('Lesson', { lessonId: lesson.id })} style={[styles.lessonCard, !unlocked && styles.lessonLocked]}><View style={styles.lessonIcon}>{completed ? <CheckCircle2 size={21} color={colors.success} /> : unlocked ? <PlayCircle size={21} color={colors.gold} /> : <Lock size={18} color={colors.textFaint} />}</View><View style={styles.lessonBody}><View style={styles.lessonTop}><Text style={styles.lessonBelt}>{belts[beltIndex]?.cefr ?? 'A0'} · LIÇÃO {String(index + 1).padStart(2, '0')}</Text>{completed && <Text style={styles.completedLabel}>CONCLUÍDA</Text>}</View><Text style={styles.lessonTitle}>{lesson.title}</Text><Text style={styles.lessonSubtitle}>{lesson.subtitle}</Text><View style={styles.lessonMeta}><Clock3 size={13} color={colors.textFaint} /><Text style={styles.metaText}>{lesson.duration}</Text><Text style={styles.dot}>·</Text><Text style={styles.metaText}>+{lesson.xpReward} XP</Text></View></View><ArrowRight size={18} color={unlocked ? colors.textMuted : colors.textFaint} /></Pressable>; })}</View><View style={styles.pathNote}><Text style={styles.noteTitle}>A cidade cresce com você.</Text><Text style={styles.noteText}>Complete lições para desbloquear novos lugares e situações do cotidiano.</Text><ProgressBar value={Math.min((profile?.completed_lessons ?? 0) / 8, 1)} color={colors.redBright} /></View></Screen>;
}

const styles = StyleSheet.create({ eyebrow: { ...typography.caption, color: colors.redBright, letterSpacing: 1.6, marginTop: spacing.sm }, title: { ...typography.display, color: colors.text, marginTop: 6 }, subtitle: { ...typography.body, color: colors.textMuted, marginTop: spacing.sm, marginBottom: spacing.xl }, streakCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: spacing.lg, backgroundColor: colors.surface, borderRadius: radii.lg, borderWidth: 1, borderColor: colors.border, marginBottom: spacing.xl }, streakLabel: { ...typography.caption, color: colors.gold }, streakTitle: { ...typography.body, color: colors.text, fontWeight: '800', marginTop: 5 }, streakValue: { color: colors.goldBright, fontSize: 40, fontWeight: '800' }, streakUnit: { fontSize: 15 }, list: { gap: spacing.sm }, lessonCard: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, backgroundColor: colors.surface, borderRadius: radii.md, padding: spacing.md, borderWidth: 1, borderColor: colors.border }, lessonLocked: { opacity: 0.52 }, lessonIcon: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surfaceElevated }, lessonBody: { flex: 1 }, lessonTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, lessonBelt: { ...typography.caption, color: colors.gold, fontSize: 10 }, completedLabel: { ...typography.caption, color: colors.success, fontSize: 9 }, lessonTitle: { ...typography.body, color: colors.text, fontWeight: '800', marginTop: 5 }, lessonSubtitle: { ...typography.caption, color: colors.textMuted, marginTop: 2, letterSpacing: 0 }, lessonMeta: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 9 }, metaText: { ...typography.caption, color: colors.textFaint, letterSpacing: 0 }, dot: { color: colors.textFaint }, pathNote: { marginTop: spacing.xl, padding: spacing.lg, backgroundColor: '#211B11', borderRadius: radii.md, borderWidth: 1, borderColor: colors.goldSoft, gap: 8 }, noteTitle: { ...typography.body, color: colors.goldBright, fontWeight: '800' }, noteText: { ...typography.body, color: colors.textMuted, fontSize: 13 } });
