import React, { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { BookOpen, Check, ChevronLeft, Flag, Headphones, MessageCircle, RotateCcw } from 'lucide-react-native';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { DemoBanner } from '../components/DemoBanner';
import { ProgressBar } from '../components/ProgressBar';
import { Screen } from '../components/Screen';
import { colors, radii, spacing, typography } from '../constants/theme';
import { starterMissions } from '../data/lessons';
import type { Mission } from '../data/lessons';
import { storage } from '../services/storage';
import { useAuth } from '../contexts/AuthContext';
import type { RootStackParamList } from '../navigation/types';

type Props = NativeStackScreenProps<RootStackParamList, 'Missions'>;
const icons: Record<string, any> = { Headphones, MessageCircle, BookOpen, Flag, RotateCcw };

export function MissionsScreen({ navigation }: Props) {
  const { demoMode } = useAuth();
  const [missionState, setMissionState] = useState<Mission[]>(starterMissions);
  useEffect(() => { storage.getMissions().then((saved) => { if (saved.length) setMissionState(saved); }); }, []);
  const completed = missionState.filter((mission) => mission.completed).length;
  function finishMission(id: string) {
    setMissionState((current) => { const next = current.map((mission) => mission.id === id ? { ...mission, progress: mission.target, completed: true } : mission); void storage.saveMissions(next); return next; });
  }
  return <Screen><Pressable style={styles.back} onPress={() => navigation.goBack()}><ChevronLeft size={18} color={colors.text} /><Text style={styles.backText}>Voltar</Text></Pressable><Text style={styles.eyebrow}>RITUAL DIÁRIO</Text><Text style={styles.title}>Missões</Text><Text style={styles.subtitle}>Cinco pequenas ações para manter o alemão perto de você.</Text>{demoMode && <DemoBanner />}<View style={styles.summary}><View><Text style={styles.summaryLabel}>MISSÕES DE HOJE</Text><Text style={styles.summaryValue}>{completed}<Text style={styles.summaryTotal}>/{missionState.length}</Text></Text></View><View style={styles.summaryProgress}><ProgressBar value={completed / missionState.length} color={colors.goldBright} /><Text style={styles.summaryHint}>{completed === missionState.length ? 'Tudo concluído.' : 'Você está no caminho.'}</Text></View></View><View style={styles.list}>{missionState.map((mission) => { const Icon = icons[mission.icon] ?? Flag; const progress = Math.min(mission.progress / mission.target, 1); return <View key={mission.id} style={[styles.card, mission.completed && styles.cardCompleted]}><View style={[styles.icon, mission.completed && styles.iconCompleted]}><Icon size={20} color={mission.completed ? colors.success : colors.gold} /></View><View style={styles.body}><View style={styles.cardTop}><Text style={styles.label}>{mission.label.toUpperCase()}</Text><Text style={[styles.status, mission.completed && styles.statusDone]}>{mission.completed ? 'CONCLUÍDA' : `+${mission.xpReward} XP`}</Text></View><Text style={styles.missionTitle}>{mission.title}</Text><View style={styles.progressRow}><ProgressBar value={progress} color={mission.completed ? colors.success : colors.goldBright} height={7} /><Text style={styles.progressText}>{mission.progress}/{mission.target}</Text></View>{!mission.completed && <Pressable onPress={() => finishMission(mission.id)} style={styles.action}><Text style={styles.actionText}>Marcar como concluída</Text><Check size={14} color={colors.gold} /></Pressable>}</View></View>; })}</View><View style={styles.note}><Text style={styles.noteTitle}>Seu idioma cresce na repetição.</Text><Text style={styles.noteText}>As missões reiniciam a cada dia quando a sincronização com o Supabase estiver ativa.</Text></View></Screen>;
}

const styles = StyleSheet.create({ back: { flexDirection: 'row', alignItems: 'center', gap: 3, marginTop: spacing.sm, marginBottom: spacing.xl }, backText: { ...typography.body, color: colors.textMuted }, eyebrow: { ...typography.caption, color: colors.redBright, letterSpacing: 1.6 }, title: { ...typography.display, color: colors.text, marginTop: 6 }, subtitle: { ...typography.body, color: colors.textMuted, marginTop: spacing.sm, marginBottom: spacing.xl }, summary: { flexDirection: 'row', alignItems: 'center', gap: spacing.lg, padding: spacing.lg, borderRadius: radii.lg, backgroundColor: '#211B11', borderWidth: 1, borderColor: colors.goldSoft, marginBottom: spacing.xl }, summaryLabel: { ...typography.caption, color: colors.gold, fontSize: 9 }, summaryValue: { fontSize: 38, fontWeight: '800', color: colors.goldBright, marginTop: 2 }, summaryTotal: { fontSize: 17, color: colors.textMuted }, summaryProgress: { flex: 1, gap: 7 }, summaryHint: { ...typography.caption, color: colors.textMuted, letterSpacing: 0 }, list: { gap: spacing.sm }, card: { flexDirection: 'row', gap: spacing.md, padding: spacing.md, backgroundColor: colors.surface, borderRadius: radii.md, borderWidth: 1, borderColor: colors.border }, cardCompleted: { borderColor: '#405844' }, icon: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#382C15', alignItems: 'center', justifyContent: 'center' }, iconCompleted: { backgroundColor: '#243526' }, body: { flex: 1 }, cardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, label: { ...typography.caption, color: colors.textFaint, fontSize: 9 }, status: { ...typography.caption, color: colors.gold, fontSize: 9 }, statusDone: { color: colors.success }, missionTitle: { ...typography.body, color: colors.text, fontWeight: '800', marginTop: 5 }, progressRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginTop: spacing.md }, progressText: { ...typography.caption, color: colors.textMuted, letterSpacing: 0 }, action: { flexDirection: 'row', alignItems: 'center', gap: 5, alignSelf: 'flex-start', marginTop: spacing.md }, actionText: { ...typography.caption, color: colors.gold, letterSpacing: 0 }, note: { marginTop: spacing.xl, padding: spacing.lg, borderRadius: radii.md, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, noteTitle: { ...typography.body, color: colors.text, fontWeight: '800' }, noteText: { ...typography.caption, color: colors.textMuted, letterSpacing: 0, marginTop: 5 } });
