import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Award, Flame, Star, Trophy } from 'lucide-react-native';
import { BottomTabScreenProps } from '@react-navigation/bottom-tabs';
import { Screen } from '../components/Screen';
import { StatCard } from '../components/StatCard';
import { SectionHeader } from '../components/SectionHeader';
import { colors, radii, spacing, typography } from '../constants/theme';
import { beltById } from '../constants/belts';
import { useAuth } from '../contexts/AuthContext';
import type { MainTabParamList } from '../navigation/types';

type Props = BottomTabScreenProps<MainTabParamList, 'Progress'>;
const chart = [{ day: 'SEG', value: 0.45 }, { day: 'TER', value: 0.7 }, { day: 'QUA', value: 0.9 }, { day: 'QUI', value: 0.35 }, { day: 'SEX', value: 0.62 }, { day: 'SÁB', value: 0.22 }, { day: 'DOM', value: 0.78 }];
export function ProgressScreen(_props: Props) {
  const { profile } = useAuth(); const belt = beltById(profile?.current_belt ?? 'white');
  return <Screen><Text style={styles.eyebrow}>SEU RITMO</Text><Text style={styles.title}>Progresso</Text><Text style={styles.subtitle}>Consistência é a sua maior conquista.</Text><View style={styles.highlight}><View><Text style={styles.highlightLabel}>XP TOTAL</Text><Text style={styles.highlightValue}>{profile?.xp ?? 0}</Text><Text style={styles.highlightMeta}>+40 esta semana</Text></View><View style={styles.trophy}><Trophy size={28} color={colors.goldBright} /></View></View><View style={styles.stats}><StatCard label="Faixa" value={belt.cefr} accent={colors.goldBright} /><StatCard label="Sequência" value={`${profile?.streak ?? 0} dias`} accent={colors.redBright} /></View><View style={[styles.stats, { marginTop: spacing.sm }]}><StatCard label="Lições" value={String(profile?.completed_lessons ?? 0)} /><StatCard label="Nível" value={belt.name.replace('Faixa ', '')} /></View><View style={styles.chartCard}><SectionHeader title="Atividade semanal" action="XP" /><View style={styles.chart}><View style={styles.gridLine} /><View style={[styles.gridLine, { top: '50%' }]} /><View style={styles.bars}>{chart.map((item) => <View key={item.day} style={styles.barGroup}><View style={styles.barTrack}><View style={[styles.bar, { height: `${item.value * 100}%` as `${number}%` }]} /></View><Text style={styles.day}>{item.day}</Text></View>)}</View></View></View><SectionHeader title="Últimas conquistas" /><View style={styles.achievement}><View style={styles.achievementIcon}><Flame size={19} color={colors.gold} /></View><View style={styles.achievementBody}><Text style={styles.achievementTitle}>Primeiro ritmo</Text><Text style={styles.achievementText}>Manteve uma sequência de 3 dias.</Text></View><Text style={styles.achievementXP}>+30 XP</Text></View><View style={styles.achievement}><View style={[styles.achievementIcon, styles.redIcon]}><Award size={19} color={colors.redBright} /></View><View style={styles.achievementBody}><Text style={styles.achievementTitle}>Primeiro passo</Text><Text style={styles.achievementText}>Concluiu sua primeira lição.</Text></View><Text style={styles.achievementXP}>+20 XP</Text></View><View style={styles.achievement}><View style={styles.achievementIcon}><Star size={19} color={colors.gold} /></View><View style={styles.achievementBody}><Text style={styles.achievementTitle}>Vocabulário em alta</Text><Text style={styles.achievementText}>Aprendeu 8 palavras novas.</Text></View><Text style={styles.achievementXP}>+25 XP</Text></View></Screen>;
}

const styles = StyleSheet.create({ eyebrow: { ...typography.caption, color: colors.redBright, letterSpacing: 1.6, marginTop: spacing.sm }, title: { ...typography.display, color: colors.text, marginTop: 6 }, subtitle: { ...typography.body, color: colors.textMuted, marginTop: spacing.sm, marginBottom: spacing.xl }, highlight: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: spacing.lg, borderRadius: radii.lg, backgroundColor: '#211B11', borderWidth: 1, borderColor: colors.goldSoft, marginBottom: spacing.md }, highlightLabel: { ...typography.caption, color: colors.gold }, highlightValue: { fontSize: 42, fontWeight: '800', color: colors.goldBright, marginTop: 2 }, highlightMeta: { ...typography.caption, color: colors.textMuted, letterSpacing: 0 }, trophy: { width: 62, height: 62, borderRadius: 31, backgroundColor: '#382C15', alignItems: 'center', justifyContent: 'center' }, stats: { flexDirection: 'row', gap: spacing.sm }, chartCard: { marginTop: spacing.xl, backgroundColor: colors.surface, borderRadius: radii.lg, borderWidth: 1, borderColor: colors.border, padding: spacing.lg, marginBottom: spacing.xl }, chart: { height: 160, position: 'relative' }, gridLine: { position: 'absolute', left: 0, right: 0, top: '25%', height: 1, backgroundColor: colors.border }, bars: { flex: 1, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', paddingTop: 14 }, barGroup: { height: '100%', alignItems: 'center', justifyContent: 'flex-end', gap: 7, width: 25 }, barTrack: { height: 118, width: 12, justifyContent: 'flex-end', backgroundColor: colors.surfaceElevated, borderRadius: radii.pill, overflow: 'hidden' }, bar: { width: '100%', backgroundColor: colors.gold, borderRadius: radii.pill }, day: { ...typography.caption, color: colors.textFaint, fontSize: 9, letterSpacing: 0 }, achievement: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, backgroundColor: colors.surface, borderRadius: radii.md, borderWidth: 1, borderColor: colors.border, padding: spacing.md, marginBottom: spacing.sm }, achievementIcon: { width: 38, height: 38, borderRadius: 19, backgroundColor: '#382C15', alignItems: 'center', justifyContent: 'center' }, redIcon: { backgroundColor: '#32191A' }, achievementBody: { flex: 1 }, achievementTitle: { ...typography.body, color: colors.text, fontWeight: '800' }, achievementText: { ...typography.caption, color: colors.textMuted, letterSpacing: 0, marginTop: 2 }, achievementXP: { ...typography.caption, color: colors.gold } });
